
# Site
title: MDP.Lab2

# Theme
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Source Code on GitHub":
    - "//github.com/Clark159/MDP.Lab2"
favicon_ico: "/favicon.ico"
color_scheme: dark
search_enabled: false

# Plugins
plugins:
  - jekyll-sitemap